"""staff_access_roster"""

import sqlalchemy as sa

from alembic import op

revision = "1d07fcb07366"
down_revision = "fb336b1dfdd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_access",
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["staff_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("merchant_id", "staff_id"),
    )
    # Retain current assignments and formerly accepted members, including revoked staff.
    op.execute("""
        INSERT INTO staff_access (merchant_id, staff_id, revision)
        SELECT merchant_id, staff_id, 1 FROM staff_assignments
        UNION
        SELECT i.merchant_id, u.id, 1 FROM staff_invitations i
        JOIN users u ON u.email = i.email
        WHERE i.accepted_at IS NOT NULL AND u.role = 'MERCHANT_STAFF'
        ON CONFLICT DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staff_access")
    # ### end Alembic commands ###
