"""shopper_advertisements"""

import sqlalchemy as sa

from alembic import op

revision = "2287259f6942"
down_revision = "1d07fcb07366"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advertisements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sponsor", sa.String(length=150), nullable=False),
        sa.Column("headline", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=False),
        sa.Column("image_alt", sa.String(length=150), nullable=False),
        sa.Column("cta", sa.String(length=60), nullable=False),
        sa.Column("placement", sa.String(length=20), nullable=False),
        sa.Column("destination_type", sa.String(length=10), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=True),
        sa.Column("offer_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "destination_type IN ('DISCOVER','STORE','OFFER')", name="advertisement_destination"
        ),
        sa.CheckConstraint(
            "placement IN ('BELOW_DAILY','BELOW_OFFERS')", name="advertisement_placement"
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ENABLED','DISABLED','ARCHIVED')", name="advertisement_status"
        ),
        sa.CheckConstraint("expires_at > starts_at", name="advertisement_dates"),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_advertisements_placement"), "advertisements", ["placement"], unique=False
    )
    op.create_index(op.f("ix_advertisements_status"), "advertisements", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_advertisements_status"), table_name="advertisements")
    op.drop_index(op.f("ix_advertisements_placement"), table_name="advertisements")
    op.drop_table("advertisements")
    # ### end Alembic commands ###
