"""coupon_redemptions"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "2405ce1bbaef"
down_revision = "5b130c143f9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "redemptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("purchase_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reward_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("receipt", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "purchase_amount >= 0 AND discount_amount >= 0 AND discount_amount <= purchase_amount",
            name="redemption_amounts",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["claim_id"], ["coupon_claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_id", "idempotency_key", name="uq_redemption_actor_request"),
        sa.UniqueConstraint("claim_id"),
    )
    op.create_index(op.f("ix_redemptions_actor_id"), "redemptions", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_redemptions_merchant_id"), "redemptions", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_redemptions_redeemed_at"), "redemptions", ["redeemed_at"], unique=False
    )
    op.create_index(op.f("ix_redemptions_store_id"), "redemptions", ["store_id"], unique=False)
    op.create_index(op.f("ix_redemptions_user_id"), "redemptions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.execute("DELETE FROM background_jobs WHERE kind = 'coupon.redeemed'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_redemptions_user_id"), table_name="redemptions")
    op.drop_index(op.f("ix_redemptions_store_id"), table_name="redemptions")
    op.drop_index(op.f("ix_redemptions_redeemed_at"), table_name="redemptions")
    op.drop_index(op.f("ix_redemptions_merchant_id"), table_name="redemptions")
    op.drop_index(op.f("ix_redemptions_actor_id"), table_name="redemptions")
    op.drop_table("redemptions")
    # ### end Alembic commands ###
