"""coupon_campaigns_claims"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "5b130c143f9b"
down_revision = "0005_offers"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupon_allowance_usage",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("used >= 0", name="allowance_used"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "period_start"),
    )
    op.create_table(
        "coupon_campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("claimed_count", sa.Integer(), nullable=False),
        sa.Column("per_user_limit", sa.Integer(), nullable=False),
        sa.Column("validity_hours", sa.Integer(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','PAUSED','CANCELLED')", name="campaign_status"
        ),
        sa.CheckConstraint("expires_at > starts_at", name="campaign_dates"),
        sa.CheckConstraint("per_user_limit > 0", name="campaign_user_limit"),
        sa.CheckConstraint(
            "total_quantity > 0 AND claimed_count >= 0 AND claimed_count <= total_quantity",
            name="campaign_stock",
        ),
        sa.CheckConstraint(
            "validity_hours IS NULL OR validity_hours > 0", name="campaign_validity"
        ),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coupon_campaigns_offer_id"), "coupon_campaigns", ["offer_id"], unique=False
    )
    op.create_table(
        "coupon_campaign_branches",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["coupon_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("campaign_id", "store_id"),
    )
    op.create_table(
        "coupon_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("claim_token", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "status IN ('CLAIMED','REDEEMED','EXPIRED','CANCELLED')", name="claim_status"
        ),
        sa.CheckConstraint("expires_at > claimed_at", name="claim_dates"),
        sa.ForeignKeyConstraint(["campaign_id"], ["coupon_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_token"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_claim_user_request"),
    )
    op.create_index(
        op.f("ix_coupon_claims_campaign_id"), "coupon_claims", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_coupon_claims_expires_at"), "coupon_claims", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_coupon_claims_user_id"), "coupon_claims", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.execute("DELETE FROM background_jobs WHERE kind IN ('coupon.claimed', 'coupon.expire')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coupon_claims_user_id"), table_name="coupon_claims")
    op.drop_index(op.f("ix_coupon_claims_expires_at"), table_name="coupon_claims")
    op.drop_index(op.f("ix_coupon_claims_campaign_id"), table_name="coupon_claims")
    op.drop_table("coupon_claims")
    op.drop_table("coupon_campaign_branches")
    op.drop_index(op.f("ix_coupon_campaigns_offer_id"), table_name="coupon_campaigns")
    op.drop_table("coupon_campaigns")
    op.drop_table("coupon_allowance_usage")
    # ### end Alembic commands ###
