"""daily_coupon_policy"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "e49fce408820"
down_revision = "2405ce1bbaef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupon_policies",
        sa.Column("version", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("version"),
        sa.UniqueConstraint("effective_at"),
    )
    op.create_table(
        "daily_picks",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["campaign_id"], ["coupon_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("store_id", "business_date", "source"),
    )
    op.create_table(
        "daily_recommendations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("identity", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["coupon_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "identity"),
    )
    # ### end Alembic commands ###
    op.execute("""INSERT INTO coupon_policies (version, effective_at, rules) VALUES
        (1, '1970-01-01T00:00:00Z', jsonb_build_object(
          'allowance', 1, 'period', 'DAILY', 'timezone', 'Asia/Kolkata',
          'default_radius_km', 5, 'max_radius_km', 10))""")
    op.execute("SELECT setval(pg_get_serial_sequence('coupon_policies','version'), 1)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_recommendations")
    op.drop_table("daily_picks")
    op.drop_table("coupon_policies")
    # ### end Alembic commands ###
