"""advanced_analytics"""

import sqlalchemy as sa

from alembic import op

revision = "f446a193c80f"
down_revision = "65a10049ec1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("bucket", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('OFFER_VIEWED','STORE_VIEWED','COUPON_VIEWED','AD_VIEWED','AD_CLICKED')",
            name="analytics_event_kind",
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "kind", "target_id", "bucket", name="analytics_event_dedup"),
    )
    op.create_index(
        op.f("ix_analytics_events_occurred_at"), "analytics_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_analytics_scope_time", "analytics_events", ["merchant_id", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_billing_payments_paid_at"), "billing_payments", ["paid_at"], unique=False
    )
    op.create_index(
        op.f("ix_billing_refunds_completed_at"), "billing_refunds", ["completed_at"], unique=False
    )
    op.create_index(
        op.f("ix_coupon_claims_claimed_at"), "coupon_claims", ["claimed_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coupon_claims_claimed_at"), table_name="coupon_claims")
    op.drop_index(op.f("ix_billing_refunds_completed_at"), table_name="billing_refunds")
    op.drop_index(op.f("ix_billing_payments_paid_at"), table_name="billing_payments")
    op.drop_index("ix_analytics_scope_time", table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_occurred_at"), table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
