"""reviews_support"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "fb336b1dfdd7"
down_revision = "8d9ae3f1be76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("redemption_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("moderation_reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('PENDING','PUBLISHED','HIDDEN')", name="review_status"),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="review_rating"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["redemption_id"], ["redemptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("redemption_id"),
    )
    op.create_index(op.f("ix_reviews_merchant_id"), "reviews", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_reviews_offer_id"), "reviews", ["offer_id"], unique=False)
    op.create_index(op.f("ix_reviews_status"), "reviews", ["status"], unique=False)
    op.create_index(op.f("ix_reviews_store_id"), "reviews", ["store_id"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "support_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("redemption_id", sa.Uuid(), nullable=True),
        sa.Column("target_type", sa.String(length=10), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=2000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('OPEN','UNDER_REVIEW','AWAITING_RESPONSE','RESOLVED')",
            name="support_status",
        ),
        sa.CheckConstraint(
            "target_type IN ('CLAIM','OFFER','STORE','REVIEW')", name="support_target"
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["coupon_claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["redemption_id"], ["redemptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporter_id", "target_type", "target_id", "reason", name="uq_report_target_reason"
        ),
    )
    op.create_index(
        op.f("ix_support_cases_merchant_id"), "support_cases", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_support_cases_reporter_id"), "support_cases", ["reporter_id"], unique=False
    )
    op.create_index(op.f("ix_support_cases_status"), "support_cases", ["status"], unique=False)
    op.create_index(op.f("ix_support_cases_store_id"), "support_cases", ["store_id"], unique=False)
    op.create_table(
        "support_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["support_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_actions_case_id"), "support_actions", ["case_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_support_actions_case_id"), table_name="support_actions")
    op.drop_table("support_actions")
    op.drop_index(op.f("ix_support_cases_store_id"), table_name="support_cases")
    op.drop_index(op.f("ix_support_cases_status"), table_name="support_cases")
    op.drop_index(op.f("ix_support_cases_reporter_id"), table_name="support_cases")
    op.drop_index(op.f("ix_support_cases_merchant_id"), table_name="support_cases")
    op.drop_table("support_cases")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_store_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_status"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_offer_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_merchant_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
